### ISSUE TITLE
updateList.js: Error: Module version mismatch. Expected 11, got 1.

### ISSUE THREAD

**Issue by LudovicRousseau** [cdesiles/node-pcsc#14]
```
$ ./tools/updateList.js 

module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: Module version mismatch. Expected 11, got 1.
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/rousseau/Documents/github/node-pcsc/node_modules/bufferstream/node_modules/buffertools/buffertools.js:1:77)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

**Comment by cdesiles** [comment]
I cannot reproduce this issue:

``` bash
$ ./tools/updateList.js 
Waiting for smartcard_list.txt...
Parsing file...
Done!
List has been saved in /home/cde/Workspace/node-pcsc/tools/../lib/smcard-list.js
```

It may be related to `bufferstream` itself, which may not support well OSX. I will avoid the use of this module.

**Comment by LudovicRousseau** [comment]
Any progress on this bug?
